#!/usr/bin/env bash
echo "== list objects"


set -e
if [ -z "$1" ]; then
    echo "No bucket name provided. Usage: $0 bucket-name"
    exit 1
fi

BUCKET_NAME=$1

aws s3api delete-bucket \
--bucket "$BUCKET_NAME"